name: BlockSounds
main: Xenophilicy\BlockSounds\BlockSounds
version: 2.0.1
author: 
  - Xenophilicy
  - BeeAZ
api: 5.0.0
permissions:
  blocksound:
    default: op
  blocksound.use:
    default: true
  blocksound.command:
    default: op
  blocksound.command.set:
    default: op
  blocksound.command.remove:
    default: op
